import type { Ingredient, IngredientCategory } from '../../features/store/model/store.types';

function ingredient(
  id: string,
  emoji: string,
  name: string,
  category: IngredientCategory,
  usesPerUnit: number,
  priceSek: number,
  aliases: string[],
  color: string,
): Ingredient {
  return {
    id,
    emoji,
    name,
    category,
    usesPerUnit,
    priceSek,
    aliases,
    isPantry: false,
    color,
  };
}

export const storeIngredients: Ingredient[] = [
  ingredient('tomato', '🍅', 'Tomato', 'Vegetables & Fruits', 3, 18, ['tomato', 'tomatoes'], '#e84b2c'),
  ingredient('onion', '🧅', 'Onion', 'Vegetables & Fruits', 3, 12, ['onion', 'onions'], '#d49a43'),
  ingredient('garlic', '🧄', 'Garlic', 'Vegetables & Fruits', 3, 14, ['garlic', 'garlic clove'], '#eee1bd'),
  ingredient('bell-pepper', '🫑', 'Bell Pepper', 'Vegetables & Fruits', 3, 22, ['red pepper', 'green pepper', 'bell pepper'], '#e33f2f'),
  ingredient('spring-onion', '🌱', 'Spring Onion', 'Vegetables & Fruits', 3, 16, ['spring onion', 'spring onions'], '#64a94c'),
  ingredient('broccoli', '🥦', 'Broccoli', 'Vegetables & Fruits', 3, 24, ['broccoli'], '#2f7a4b'),
  ingredient('cucumber', '🥒', 'Cucumber', 'Vegetables & Fruits', 3, 16, ['cucumber'], '#5f9f4d'),
  ingredient('sweetcorn', '🌽', 'Sweetcorn', 'Vegetables & Fruits', 3, 17, ['sweetcorn'], '#f2bc39'),
  ingredient('spinach', '🥬', 'Spinach', 'Vegetables & Fruits', 3, 21, ['spinach'], '#35744b'),
  ingredient('cabbage', '🥬', 'Cabbage', 'Vegetables & Fruits', 3, 19, ['cabbage'], '#7fae66'),
  ingredient('lettuce', '🥬', 'Lettuce', 'Vegetables & Fruits', 3, 20, ['lettuce'], '#6cb85a'),
  ingredient('zucchini', '🥒', 'Zucchini', 'Vegetables & Fruits', 3, 20, ['zucchini', 'courgette'], '#4c8d4b'),
  ingredient('peas', '🟢', 'Peas', 'Vegetables & Fruits', 3, 18, ['peas'], '#54a847'),
  ingredient('green-beans', '🫛', 'Green Beans', 'Vegetables & Fruits', 3, 23, ['green beans'], '#3d8843'),
  ingredient('celery', '🥬', 'Celery', 'Vegetables & Fruits', 3, 18, ['celery'], '#7fbf66'),
  ingredient('leek', '🧅', 'Leek', 'Vegetables & Fruits', 3, 20, ['leek'], '#7ba55c'),
  ingredient('cauliflower', '🥦', 'Cauliflower', 'Vegetables & Fruits', 3, 25, ['cauliflower'], '#e6dfc6'),
  ingredient('chilli', '🌶️', 'Chilli', 'Vegetables & Fruits', 3, 15, ['chilli', 'chillies'], '#d93a2f'),
  ingredient('eggplant', '🍆', 'Eggplant', 'Vegetables & Fruits', 3, 24, ['aubergine', 'eggplant'], '#5b3f72'),
  ingredient('potatoes', '🥔', 'Potatoes', 'Vegetables & Fruits', 3, 20, ['potato', 'potatoes'], '#b78b56'),
  ingredient('sweet-potatoes', '🍠', 'Sweet Potatoes', 'Vegetables & Fruits', 3, 24, ['sweet potato', 'sweet potatoes'], '#c46e3b'),
  ingredient('carrots', '🥕', 'Carrots', 'Vegetables & Fruits', 3, 17, ['carrot', 'carrots'], '#ec7a2d'),
  ingredient('mushrooms', '🍄', 'Mushrooms', 'Vegetables & Fruits', 3, 26, ['mushroom', 'mushrooms'], '#a88768'),
  ingredient('apple', '🍎', 'Apple', 'Vegetables & Fruits', 3, 15, ['apple', 'apples'], '#d63c35'),
  ingredient('banana', '🍌', 'Banana', 'Vegetables & Fruits', 3, 14, ['banana', 'bananas'], '#edc84a'),
  ingredient('lemon', '🍋', 'Lemon', 'Vegetables & Fruits', 3, 13, ['lemon'], '#f1c735'),
  ingredient('lime', '🍋', 'Lime', 'Vegetables & Fruits', 3, 14, ['lime'], '#75a83e'),
  ingredient('avocado', '🥑', 'Avocado', 'Vegetables & Fruits', 3, 29, ['avocado'], '#628446'),
  ingredient('canned-tomatoes', '🥫', 'Canned Tomatoes', 'Vegetables & Fruits', 3, 18, ['canned tomatoes'], '#c74231'),
  ingredient('tomato-puree', '🥫', 'Tomato Puree', 'Vegetables & Fruits', 3, 16, ['tomato puree'], '#a92e26'),
  ingredient('chicken-breast', '🍗', 'Chicken Breast', 'Meat & Seafood', 1, 58, ['chicken breast'], '#d69a78'),
  ingredient('beef', '🥩', 'Beef', 'Meat & Seafood', 1, 74, ['beef'], '#9d3e36'),
  ingredient('minced-beef', '🥩', 'Minced Beef', 'Meat & Seafood', 1, 62, ['minced beef', 'ground beef'], '#a64b42'),
  ingredient('bacon', '🥓', 'Bacon', 'Meat & Seafood', 3, 42, ['bacon'], '#bd594d'),
  ingredient('ham', '🍖', 'Ham', 'Meat & Seafood', 3, 40, ['ham'], '#d77e79'),
  ingredient('lamb', '🐑', 'Lamb', 'Meat & Seafood', 1, 79, ['lamb'], '#9d4d43'),
  ingredient('pork', '🐖', 'Pork', 'Meat & Seafood', 1, 61, ['pork'], '#d38378'),
  ingredient('prawns', '🦐', 'Prawns', 'Meat & Seafood', 1, 69, ['prawns', 'shrimp'], '#e27a5b'),
  ingredient('salmon', '🐟', 'Salmon', 'Meat & Seafood', 1, 78, ['salmon'], '#e87961'),
  ingredient('tuna', '🐠', 'Tuna', 'Meat & Seafood', 3, 39, ['tuna'], '#718a9d'),
  ingredient('cod', '🐟', 'Cod', 'Meat & Seafood', 1, 66, ['cod'], '#d2d9d5'),
  ingredient('sausages', '🌭', 'Sausages', 'Meat & Seafood', 3, 43, ['sausage', 'sausages'], '#b95d47'),
  ingredient('egg', '🥚', 'Egg', 'Dairy & Eggs', 3, 24, ['egg', 'eggs'], '#efc958'),
  ingredient('cheese', '🧀', 'Cheese', 'Dairy & Eggs', 3, 35, ['cheese'], '#edb43a'),
  ingredient('mozzarella', '🧀', 'Mozzarella', 'Dairy & Eggs', 3, 39, ['mozzarella'], '#efe3be'),
  ingredient('feta', '🧀', 'Feta', 'Dairy & Eggs', 3, 42, ['feta', 'feta cheese'], '#eee6cf'),
  ingredient('parmesan', '🧀', 'Parmesan', 'Dairy & Eggs', 3, 44, ['parmesan'], '#e6c66f'),
  ingredient('milk', '🥛', 'Milk', 'Dairy & Eggs', 5, 22, ['milk'], '#e9f0ef'),
  ingredient('butter', '🧈', 'Butter', 'Dairy & Eggs', 3, 31, ['butter'], '#f2c950'),
  ingredient('cream', '🥛', 'Cream', 'Dairy & Eggs', 3, 33, ['cream'], '#f2ead8'),
  ingredient('yogurt', '🥣', 'Yogurt', 'Dairy & Eggs', 3, 27, ['yogurt', 'yoghurt'], '#f0e8d8'),
  ingredient('cream-cheese', '🧀', 'Cream Cheese', 'Dairy & Eggs', 3, 36, ['cream cheese'], '#eee7d4'),
  ingredient('bread', '🍞', 'Bread', 'Grains & Staples', 3, 25, ['bread'], '#bd7c45'),
  ingredient('rice', '🍚', 'Rice', 'Grains & Staples', 3, 26, ['rice'], '#e7dfc9'),
  ingredient('spaghetti', '🍝', 'Spaghetti', 'Grains & Staples', 3, 28, ['spaghetti'], '#e1b64c'),
  ingredient('noodles', '🍜', 'Noodles', 'Grains & Staples', 3, 26, ['noodles'], '#d8af4c'),
  ingredient('flour', '🌾', 'Flour', 'Grains & Staples', 3, 19, ['flour', 'plain flour'], '#e9dfc8'),
  ingredient('sugar', '🍬', 'Sugar', 'Grains & Staples', 3, 18, ['sugar'], '#e7e4df'),
  ingredient('lentils', '🟤', 'Lentils', 'Grains & Staples', 3, 24, ['lentil', 'lentils'], '#9a6b44'),
  ingredient('chickpeas', '🫘', 'Chickpeas', 'Grains & Staples', 3, 25, ['chickpea', 'chickpeas'], '#d4ab67'),
  ingredient('oats', '🥣', 'Oats', 'Grains & Staples', 3, 23, ['oat', 'oats'], '#c4a774'),
  ingredient('tortillas', '🌮', 'Tortillas', 'Grains & Staples', 3, 27, ['tortilla', 'tortillas'], '#d5ac68'),
  ingredient('breadcrumbs', '🍞', 'Breadcrumbs', 'Grains & Staples', 3, 21, ['breadcrumbs'], '#b77d43'),
  ingredient('tofu', '⬜', 'Tofu', 'Grains & Staples', 3, 24, ['tofu'], '#ede5cf'),
  ingredient('kidney-beans', '🫘', 'Kidney Beans', 'Grains & Staples', 3, 24, ['kidney bean', 'kidney beans'], '#98443c'),
  ingredient('puff-pastry', '🥐', 'Puff Pastry', 'Grains & Staples', 3, 35, ['puff pastry'], '#d6a35f'),
  ingredient('rice-noodles', '🍜', 'Rice Noodles', 'Grains & Staples', 3, 27, ['rice noodles'], '#e0d4b8'),
  ingredient('yeast', '🍞', 'Yeast', 'Grains & Staples', 3, 15, ['yeast'], '#b99b70'),
  ingredient('coconut-milk', '🥥', 'Coconut Milk', 'Other Ingredients', 3, 29, ['coconut milk'], '#eee4cf'),
  ingredient('honey', '🍯', 'Honey', 'Other Ingredients', 3, 32, ['honey'], '#d98e24'),
  ingredient('maple-syrup', '🍁', 'Maple Syrup', 'Other Ingredients', 3, 38, ['maple syrup'], '#9f5b31'),
  ingredient('peanut-butter', '🥜', 'Peanut Butter', 'Other Ingredients', 3, 31, ['peanut butter'], '#a36d3e'),
  ingredient('jam', '🍓', 'Jam', 'Other Ingredients', 3, 27, ['jam'], '#b8394a'),
  ingredient('almonds', '🌰', 'Almonds', 'Other Ingredients', 3, 34, ['almond', 'almonds'], '#b88759'),
  ingredient('walnuts', '🌰', 'Walnuts', 'Other Ingredients', 3, 35, ['walnut', 'walnuts'], '#9d6d45'),
  ingredient('raisins', '🍇', 'Raisins', 'Other Ingredients', 3, 24, ['raisin', 'raisins'], '#68434b'),
  ingredient('ice-cream', '🍨', 'Ice Cream', 'Other Ingredients', 3, 33, ['ice cream'], '#f2d4cf'),
  ingredient('orange-juice', '🧃', 'Orange Juice', 'Other Ingredients', 3, 28, ['orange juice'], '#eb982d'),
  ingredient('chocolate', '🍫', 'Chocolate', 'Other Ingredients', 3, 30, ['chocolate'], '#6b3d2c'),
  ingredient('ginger', '🫚', 'Ginger', 'Other Ingredients', 3, 17, ['ginger'], '#c4a15d'),
];

